create table if not exists ai_settings (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  ai_name text not null default 'Ana',
  avatar_url text,
  ai_color text not null default '#00AFFF',
  voice_tone text not null default 'casual',
  greeting_message text not null default 'Oi! Eu sou a Ana, assistente virtual do restaurante. Como posso ajudar?',
  after_hours_message text not null default 'Estamos fora do horario de atendimento. Assim que voltarmos, te respondemos por aqui.',
  active_start_time text not null default '09:00',
  active_end_time text not null default '22:00',
  normal_delivery_time text not null default '30 a 40 min',
  peak_days text[] not null default '{}'::text[],
  peak_start_time text not null default '18:00',
  peak_end_time text not null default '21:00',
  peak_delivery_time text not null default '50 a 70 min',
  confirm_address boolean not null default true,
  ask_payment_method boolean not null default true,
  accepted_payment_methods text[] not null default '{pix,cartao,dinheiro}'::text[],
  delivery_fee text not null default 'R$5 ate 3km',
  served_neighborhoods text not null default '',
  minimum_order numeric(12,2) not null default 0,
  local_pickup boolean not null default true,
  auto_offer_addons boolean not null default false,
  upsell_categories text[] not null default '{}'::text[],
  offer_combos boolean not null default false,
  upsell_phrase text not null default 'Quer adicionar borda recheada?',
  active_coupon text not null default '',
  recover_inactive_customer boolean not null default false,
  post_sale_message text not null default 'Obrigado pelo pedido! Conta pra gente se estava tudo certinho.',
  do_not_invent_products boolean not null default true,
  do_not_discount_without_permission boolean not null default true,
  do_not_promise_impossible_delivery boolean not null default true,
  do_not_reply_outside_restaurant boolean not null default true,
  max_discount_percent integer not null default 0,
  forbidden_words text[] not null default '{}'::text[],
  whatsapp_status text not null default 'disconnected',
  auto_replies_enabled boolean not null default false,
  temporarily_paused boolean not null default false,
  transfer_to_human boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  is_deleted boolean not null default false
);

create unique index if not exists ai_settings_restaurant_id_unique_idx on ai_settings(restaurant_id);
